---
title: "Tidy Tuesday - SAFI Survey"
author: "Amy Mitchell-Whittington"
date: '13-06-2023'
output: github_document
---

## SAFI (Studying African Farmer-Led Irrigation) Survey

The data this week comes from the [SAFI (Studying African Farmer-Led Irrigation) survey](https://datacarpentry.org/socialsci-workshop/data/), a subset of the data used in the Data Carpentry Social Sciences workshop.

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 


library(tidyverse)
library(tidytuesdayR)
library(ggplot2)
library(ggtext)

safi_data <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-06-13/safi_data.csv')

summary(safi_data)
```

```{r plot, echo=FALSE, dpi=300}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

#separate "months_lack_food" column by ";", group by the month and find how many households lacked enough food in each month across the three villages.
df <- safi_data %>%
  separate_rows(months_lack_food, sep = ";") %>%
  mutate(months_lack_food = gsub("July", "Jul", months_lack_food)) %>%
  mutate(months_lack_food = gsub("June", "Jun", months_lack_food)) %>%
  mutate(months_lack_food = gsub("Sept", "Sep", months_lack_food)) %>%
  mutate(season = ifelse(months_lack_food %in% c("Jan", "Feb", "Mar", "Oct", "Nov", "Dec"), "Hot and Humid Season", "Cool and Dry Season")) %>%
  group_by(season, months_lack_food, village) %>%
  summarise(count = n()) %>%
  filter(months_lack_food != "none")

#plot
df %>% 
  ggplot(aes(x = months_lack_food, y = count, fill = village)) +
  geom_bar(position="dodge", stat="identity") +
  scale_x_discrete(limits = month.abb) +
  scale_y_continuous(breaks = c(seq(from = 0, to = 40, by = 2))) +
  theme_classic() +
  theme(plot.title = element_markdown(size = 13, face = "bold"),
        plot.subtitle = element_text(size = 7),
        plot.caption = element_text(size = 6, face = "italic"),
        panel.background = element_rect(fill = "ivory"),
        plot.background = element_rect(fill = "ivory2"),
        legend.background = element_rect(fill = "ivory2"),
         panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line( size=.1, color="ivory3")) +
  scale_fill_manual(values = c("blue4", "green4", "orange")) +
  labs(title = "Food insecurity in East Africa",
       subtitle = "Between 2016-2017, 131 households from three villages across Mozambique and Tanzania were asked about their living conditions\nas part of a survey run by the Studying African Farmer-Led Irrigation group. Almost three quarters of respondents said\nthey'd faced at least one month of not having enough food to feed their household in the previous year.",
       caption = "Data source: SAFI (Studying African Farmer-Led Irrigation) survey.",
       x = "Month",
       y = "Number of households without enough food",
       fill = "Villages")
```
